<template>
  <div class="flex flex-col items-stretch pb-6">
    <van-cell-group
      inset
      title="系统管理"
    >
      <van-cell
        icon-prefix="bi"
        icon="megaphone"
        title="发布公告"
        center
        is-link
        to="/announcements/create"
      />
      <van-cell
        icon-prefix="bi"
        icon="people"
        title="管理员列表"
        center
        is-link
        to="/admin/admins"
      />
    </van-cell-group>

    <van-cell-group
      inset
      title="服务器管理"
    >
      <van-cell
        icon-prefix="bi"
        icon="hdd"
        title="系统状态"
        center
        is-link
        to="/admin/server-status"
      />
    </van-cell-group>
  </div>
</template>
<script setup lang="ts">
</script>
